- hosts: web
  become: true
  tasks:
  - name: Create a file
    file: path=/var/www/html/index.html state=touch
  - name: Append file
    lineinfile:
     path: /var/www/html/index.html
     line: 'Hello World'
     owner: ubuntu
     group: ubuntu
     mode: '0777'
